/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_test_jni_DataHelper */

#ifndef _Included_java_test_jni_DataHelper
#define _Included_java_test_jni_DataHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_test_jni_DataHelper
 * Method:    ngetData
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_test_jni_DataHelper_ngetData
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_test_jni_DataHelper
 * Method:    nstoreData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_test_jni_DataHelper_nstoreData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
