/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_JNI_Helper_Dynamic */

#ifndef _Included_JNI_JNI_Helper_Dynamic
#define _Included_JNI_JNI_Helper_Dynamic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_JNI_Helper_Dynamic
 * Method:    computeExpo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_JNI_1Helper_1Dynamic_computeExpo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_JNI_Helper_Dynamic
 * Method:    getNumberFor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNI_JNI_1Helper_1Dynamic_getNumberFor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
