/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_JNI_Helper_Static */

#ifndef _Included_JNI_JNI_Helper_Static
#define _Included_JNI_JNI_Helper_Static
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_JNI_Helper_Static
 * Method:    computeExpoStatic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_JNI_1Helper_1Static_computeExpoStatic
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     JNI_JNI_Helper_Static
 * Method:    computeExpoStaticV2
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_JNI_1Helper_1Static_computeExpoStaticV2
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
